[package]
name = "tedge-datalayer-bridge"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tedge-datalayer-bridge"
path = "src/main.rs"

[[bin]]
name = "tedge-log-upload-manager"
path = "src/log_upload_manager.rs"

[dependencies]
paho-mqtt = "0.12"
tokio = { version = "1.45", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
anyhow = "1.0"
ctrlc = "3.4"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
uuid = { version = "1.11", features = ["v4"] }
futures = "0.3.32"
rumqttc = "0.25"
actix-web = "4.0"
toml = "0.8"
glob = "0.3"
chrono = "0.4"

[features]
default = ["mqtt"]
mqtt = []