//! tedge-log-upload-manager
//!
//! Implements the thin-edge.io log upload protocol for the ctrlX CORE snap:
//!  1. Reads tedge-log-plugin.toml and announces available log types every 10 min
//!  2. Listens for log upload requests from the cloud (via c8y-mapper)
//!  3. Collects matching log files, uploads them to the local tedge file-transfer service
//!  4. Reports success or failure back via MQTT

use anyhow::{Context, Result};
use glob::glob;
use reqwest::Client;
use rumqttc::{AsyncClient, Event, MqttOptions, Packet, QoS};
use serde::Deserialize;
use std::{env, path::PathBuf, time::Duration};
use tokio::{fs, time};

const MQTT_CLIENT_ID: &str = "tedge-log-upload-manager";
const LOG_UPLOAD_TOPIC: &str = "te/device/main///cmd/log_upload";
const LOG_UPLOAD_SUBSCRIBE: &str = "te/device/main///cmd/log_upload/+";
const HEALTH_TOPIC: &str = "te/device/main/service/tedge-log-upload-manager/status/health";
const HEALTH_CHECK_TOPIC: &str = "te/device/main/service/tedge-log-upload-manager/cmd/health/check";
const SERVICE_REG_TOPIC: &str = "te/device/main/service/tedge-log-upload-manager";
const ANNOUNCE_INTERVAL_SECS: u64 = 3600; // 1 hour

/// Twin topic for installed snaps — published as retained c8y_SoftwareList fragment.
/// The c8y-mapper forwards this to the Cumulocity managed object, making all installed
/// snaps visible in the Cumulocity Software tab with softwareType="snap".
/// The inventory is generated by the install/post-refresh hook via `snap list`
/// and written to $SNAP_DATA/tedge/snap-inventory.json.
const SNAP_INVENTORY_TOPIC: &str = "te/device/main///twin/c8y_SoftwareList";

// ─── Config Types ────────────────────────────────────────────────────────────

#[derive(Deserialize, Debug, Default)]
struct LogPluginConfig {
    #[serde(default)]
    files: Vec<LogFileEntry>,
}

#[derive(Deserialize, Debug, Clone)]
struct LogFileEntry {
    #[serde(rename = "type")]
    log_type: String,
    path: String,
}

// ─── MQTT Payload Types ───────────────────────────────────────────────────────

/// Quick status-only parse to decide whether to process the message at all
#[derive(Deserialize)]
struct StatusOnly {
    #[serde(default)]
    status: String,
}

/// Incoming log upload request from c8y-mapper
#[derive(Deserialize, Debug)]
struct LogUploadRequest {
    #[serde(rename = "tedgeUrl")]
    tedge_url: String,
    #[serde(rename = "type")]
    log_type: String,
    #[serde(default = "default_lines")]
    lines: usize,
    /// ISO-8601 date string from C8Y (e.g. "2026-05-21T08:57:12+0200")
    #[serde(rename = "dateFrom", default)]
    date_from: Option<String>,
    #[serde(rename = "dateTo", default)]
    date_to: Option<String>,
}

fn default_lines() -> usize {
    1000
}

/// Build a status-update payload by cloning the original request and overriding only
/// `status` (and optionally `reason`). This ensures required fields like `tedgeUrl`
/// are always echoed back so the c8y-mapper can parse the response.
fn make_status_payload(original: &serde_json::Value, status: &str, reason: Option<&str>) -> String {
    let mut v = original.clone();
    if let Some(obj) = v.as_object_mut() {
        obj.insert("status".into(), serde_json::Value::String(status.into()));
        match reason {
            Some(r) => {
                obj.insert("reason".into(), serde_json::Value::String(r.into()));
            }
            None => {
                obj.remove("reason");
            }
        }
    }
    v.to_string()
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

fn get_config_path() -> PathBuf {
    let snap_data = env::var("SNAP_DATA").unwrap_or_default();
    PathBuf::from(snap_data).join("tedge/plugins/tedge-log-plugin.toml")
}

// ─── Snap Inventory ───────────────────────────────────────────────────────────

/// Query snap list via `snap list --json` — works when snapd-control interface is connected.
/// Returns None if snapd-control is not connected (command fails or returns empty).
fn query_snap_list() -> Option<Vec<serde_json::Value>> {
    let out = std::process::Command::new("snap")
        .args(["list", "--json"])
        .output()
        .ok()?;

    if !out.status.success() {
        return None;
    }

    let parsed: serde_json::Value = serde_json::from_slice(&out.stdout).ok()?;
    // `snap list --json` returns either a JSON array or {"snaps": [...]}
    let snaps_arr = if parsed.is_array() {
        parsed.as_array()?.clone()
    } else {
        parsed.get("snaps")?.as_array()?.clone()
    };

    let result: Vec<serde_json::Value> = snaps_arr
        .iter()
        .filter_map(|s| {
            let name = s.get("name")?.as_str()?;
            let version = s.get("version").and_then(|v| v.as_str()).unwrap_or("?");
            let rev = s.get("revision").and_then(|r| r.as_str()).unwrap_or("?");
            Some(serde_json::json!({
                "name": name,
                "version": version,
                "url": format!("rev:{}", rev),
                "softwareType": "snap"
            }))
        })
        .collect();

    if result.is_empty() {
        None
    } else {
        log::info!("[SNAP-INV] snap list: found {} snaps", result.len());
        Some(result)
    }
}

/// Fallback: scan /snap/*/current/meta/snap.yaml — readable in hook context.
/// In service context this may be AppArmor-blocked, but is tried as secondary fallback.
fn query_yaml_scan() -> Option<Vec<serde_json::Value>> {
    let mut entries = Vec::new();
    let pattern = "/snap/*/current/meta/snap.yaml";
    let paths = match glob::glob(pattern) {
        Ok(p) => p,
        Err(_) => return None,
    };
    for entry in paths.flatten() {
        let content = match std::fs::read_to_string(&entry) {
            Ok(c) => c,
            Err(_) => continue,
        };
        let mut name: Option<String> = None;
        let mut version: Option<String> = None;
        for line in content.lines() {
            if name.is_none() && line.starts_with("name:") {
                name = Some(line[5..].trim().trim_matches('"').to_string());
            } else if version.is_none() && line.starts_with("version:") {
                version = Some(line[8..].trim().trim_matches('"').to_string());
            }
        }
        if let Some(n) = name {
            let snap_dir = entry.to_string_lossy().replace("/meta/snap.yaml", "");
            let rev = std::fs::read_link(&snap_dir)
                .ok()
                .and_then(|p| p.file_name().map(|f| f.to_string_lossy().into_owned()))
                .unwrap_or_else(|| "?".to_string());
            entries.push(serde_json::json!({
                "name": n,
                "version": version.unwrap_or_else(|| "?".to_string()),
                "url": format!("rev:{}", rev),
                "softwareType": "snap"
            }));
        }
    }
    if entries.is_empty() {
        None
    } else {
        log::info!("[SNAP-INV] yaml scan: found {} snaps", entries.len());
        Some(entries)
    }
}

/// Last resort: build inventory from env vars — always works, current snap only.
fn snap_inventory_from_env() -> Vec<serde_json::Value> {
    let name = std::env::var("SNAP_NAME").unwrap_or_default();
    let version = std::env::var("SNAP_VERSION").unwrap_or_default();
    let rev = std::env::var("SNAP_REVISION").unwrap_or_default();
    if name.is_empty() {
        return vec![];
    }
    log::warn!("[SNAP-INV] Falling back to env vars — only current snap visible: {name} {version}");
    vec![serde_json::json!({
        "name": name,
        "version": version,
        "url": format!("rev:{}", rev),
        "softwareType": "snap"
    })]
}

/// Read the snap inventory. Priority:
/// 1. snap-inventory.json written by install/post-refresh hook
/// 2. snapd REST API via Unix socket (may be blocked by AppArmor on some systems)
/// 3. $SNAP_NAME/$SNAP_VERSION/$SNAP_REVISION env vars (always works, current snap only)
fn collect_installed_snaps(snap_data: &str) -> Vec<serde_json::Value> {
    let path = PathBuf::from(snap_data).join("snap-inventory.json");
    match std::fs::read_to_string(&path) {
        Ok(content) => {
            let all: Vec<serde_json::Value> = serde_json::from_str(&content).unwrap_or_else(|e| {
                log::warn!("Failed to parse snap-inventory.json: {e}");
                vec![]
            });
            // Filter out stale/corrupt entries (e.g. name="*" from old glob-based hook)
            let filtered: Vec<_> = all
                .into_iter()
                .filter(|e| {
                    e.get("name")
                        .and_then(|n| n.as_str())
                        .map(|n| !n.is_empty() && n != "*")
                        .unwrap_or(false)
                })
                .collect();
            if !filtered.is_empty() {
                log::info!("[SNAP-INV] snap-inventory.json: {} snaps", filtered.len());
                return filtered;
            }
            log::warn!("[SNAP-INV] snap-inventory.json was empty or all entries filtered");
            query_snap_list()
                .or_else(query_yaml_scan)
                .unwrap_or_else(snap_inventory_from_env)
        }
        Err(_) => {
            log::warn!(
                "[SNAP-INV] snap-inventory.json not found at {}, trying snap list",
                path.display()
            );
            query_snap_list()
                .or_else(query_yaml_scan)
                .unwrap_or_else(snap_inventory_from_env)
        }
    }
}

/// Publish installed snaps as a retained c8y_SoftwareList twin fragment.
/// The c8y-mapper maps this to PUT /inventory/managedObjects/<id>
/// making snaps visible in the Cumulocity Software tab with softwareType="snap".
async fn announce_installed_snaps(client: &AsyncClient, snap_data: &str) {
    let snaps = collect_installed_snaps(snap_data);
    if snaps.is_empty() {
        log::debug!("snap-inventory.json empty or missing — skipping snap inventory publish");
        return;
    }
    let payload = serde_json::to_string(&snaps).unwrap_or_else(|_| "[]".to_string());
    match client
        .publish(SNAP_INVENTORY_TOPIC, QoS::AtLeastOnce, true, payload)
        .await
    {
        Ok(_) => log::info!("Published snap inventory: {} snaps", snaps.len()),
        Err(e) => log::error!("Failed to publish snap inventory: {e}"),
    }
}

async fn read_log_plugin_config(config_path: &PathBuf) -> Result<LogPluginConfig> {
    let content = fs::read_to_string(config_path)
        .await
        .with_context(|| format!("Cannot read {}", config_path.display()))?;
    toml::from_str(&content).context("Failed to parse tedge-log-plugin.toml")
}

/// Call the journald log plugin's `list` command and return the type names.
/// Returns empty vec on any error (best-effort, non-fatal).
fn list_journald_log_types() -> Vec<String> {
    let snap = std::env::var("SNAP").unwrap_or_default();
    let plugin = format!("{snap}/scripts/log-plugins/journald");
    match std::process::Command::new(&plugin).arg("list").output() {
        Ok(out) if out.status.success() => String::from_utf8_lossy(&out.stdout)
            .lines()
            .map(|l| l.trim().to_string())
            .filter(|l| !l.is_empty())
            .collect(),
        Ok(out) => {
            log::warn!("journald plugin list failed: {}", String::from_utf8_lossy(&out.stderr));
            vec![]
        }
        Err(e) => {
            log::warn!("Cannot run journald plugin at {plugin}: {e}");
            vec![]
        }
    }
}

/// Publish retained log-types announcement
async fn announce_log_types(client: &AsyncClient, config_path: &PathBuf) {
    match read_log_plugin_config(config_path).await {
        Ok(config) => {
            let mut types: Vec<String> = config.files.iter().map(|f| f.log_type.clone()).collect();
            // Append journald service log types with ::journald suffix
            for t in list_journald_log_types() {
                types.push(format!("{}::journald", t));
            }
            let type_refs: Vec<&str> = types.iter().map(|s| s.as_str()).collect();
            let payload = serde_json::json!({ "types": type_refs }).to_string();
            match client
                .publish(LOG_UPLOAD_TOPIC, QoS::AtLeastOnce, true, payload)
                .await
            {
                Ok(_) => log::info!("Announced log types: {:?}", type_refs),
                Err(e) => log::error!("Failed to announce log types: {e}"),
            }
        }
        Err(e) => log::warn!("Could not read log plugin config (not fatal): {e}"),
    }
}

/// Collect logs via the journald plugin script for a given service short name.
async fn collect_journald_logs(
    service: &str,
    max_lines: usize,
    date_from: Option<&str>,
    date_to: Option<&str>,
) -> anyhow::Result<String> {
    let snap = std::env::var("SNAP").unwrap_or_default();
    let plugin = format!("{snap}/scripts/log-plugins/journald");
    let mut cmd = tokio::process::Command::new(&plugin);
    cmd.arg("get").arg(service);
    if let Some(from) = date_from {
        // Parse ISO-8601 to seconds-since-epoch for the plugin's --since argument
        if let Ok(ts) = chrono::DateTime::parse_from_rfc3339(&normalise_date(from)) {
            cmd.arg("--since").arg(ts.timestamp().to_string());
        }
    }
    if let Some(to) = date_to {
        if let Ok(ts) = chrono::DateTime::parse_from_rfc3339(&normalise_date(to)) {
            cmd.arg("--until").arg(ts.timestamp().to_string());
        }
    }
    let out = cmd.output().await
        .with_context(|| format!("Cannot run journald plugin for service '{service}'"))?;
    let content = String::from_utf8_lossy(&out.stdout).to_string();
    let lines: Vec<&str> = content.lines().collect();
    let start = lines.len().saturating_sub(max_lines);
    Ok(lines[start..].join("\n"))
}

/// Normalise a C8Y date string to RFC 3339 (handles "+0200" → "+02:00").
fn normalise_date(s: &str) -> String {
    // C8Y uses "+0200" without colon; chrono needs "+02:00"
    if s.len() >= 5 {
        let offset_start = s.len() - 5;
        let maybe_offset = &s[offset_start..];
        if (maybe_offset.starts_with('+') || maybe_offset.starts_with('-'))
            && !maybe_offset.contains(':')
        {
            return format!("{}:{}", &s[..offset_start + 3], &s[offset_start + 3..]);
        }
    }
    s.to_string()
}

/// Expand glob pattern, read matching files (sorted oldest→newest), return last `max_lines` lines
async fn collect_log_content(path_pattern: &str, max_lines: usize) -> Result<String> {
    let mut paths: Vec<(PathBuf, std::time::SystemTime)> = glob(path_pattern)
        .with_context(|| format!("Invalid glob: {path_pattern}"))?
        .filter_map(|r| r.ok())
        .filter_map(|p| {
            let mtime = std::fs::metadata(&p).ok()?.modified().ok()?;
            Some((p, mtime))
        })
        .collect();

    if paths.is_empty() {
        anyhow::bail!("No log files found matching: {path_pattern}");
    }

    // Oldest file first so chronological order is preserved
    paths.sort_by_key(|(_, t)| *t);

    let mut all_lines: Vec<String> = Vec::new();
    for (path, _) in &paths {
        match fs::read_to_string(path).await {
            Ok(content) => all_lines.extend(content.lines().map(String::from)),
            Err(e) => log::warn!("Skipping {}: {e}", path.display()),
        }
    }

    let start = all_lines.len().saturating_sub(max_lines);
    Ok(all_lines[start..].join("\n"))
}

// ─── Request Handler ──────────────────────────────────────────────────────────

async fn handle_log_upload_request(
    client: &AsyncClient,
    http: &Client,
    topic: &str,
    payload: &[u8],
    config_path: &PathBuf,
) {
    // Skip empty payloads (MQTT retained-clear messages)
    if payload.is_empty() {
        return;
    }

    // Check status first with a lightweight parse to avoid noisy errors
    // for our own executing/successful callbacks coming back via MQTT.
    let status: String = match serde_json::from_slice::<StatusOnly>(payload) {
        Ok(s) => s.status,
        Err(_) => return, // unparseable → not our message
    };
    if status != "scheduled" && status != "init" {
        return;
    }

    // Full parse only for actionable states
    let request: LogUploadRequest = match serde_json::from_slice(payload) {
        Ok(r) => r,
        Err(e) => {
            log::error!("Cannot parse log upload request on {topic}: {e}");
            return;
        }
    };

    log::info!(
        "Log upload request: type='{}', lines={}, url={}",
        request.log_type,
        request.lines,
        request.tedge_url
    );

    // Parse original payload as Value so we can echo it back in all responses
    let original: serde_json::Value = serde_json::from_slice(payload).unwrap_or_default();

    // Acknowledge: "executing" — non-retained, no need to clear
    let _ = client
        .publish(
            topic,
            QoS::AtLeastOnce,
            false,
            make_status_payload(&original, "executing", None),
        )
        .await;

    // Route: journald plugin types have suffix ::journald
    let content = if let Some(service) = request.log_type.strip_suffix("::journald") {
        match collect_journald_logs(
            service,
            request.lines,
            request.date_from.as_deref(),
            request.date_to.as_deref(),
        )
        .await
        {
            Ok(c) => c,
            Err(e) => {
                let reason = format!("Failed to read journald logs for '{service}': {e}");
                log::error!("{reason}");
                publish_final(client, topic, &original, "failed", Some(&reason)).await;
                return;
            }
        }
    } else {
        // File-based log type — look up in tedge-log-plugin.toml
        let config = match read_log_plugin_config(config_path).await {
            Ok(c) => c,
            Err(e) => {
                publish_final(client, topic, &original, "failed", Some(&e.to_string())).await;
                return;
            }
        };
        let entry = match config.files.iter().find(|f| f.log_type == request.log_type) {
            Some(e) => e.clone(),
            None => {
                let reason = format!("Unknown log type: '{}'", request.log_type);
                log::error!("{reason}");
                publish_final(client, topic, &original, "failed", Some(&reason)).await;
                return;
            }
        };
        match collect_log_content(&entry.path, request.lines).await {
            Ok(c) => c,
            Err(e) => {
                let reason = format!("Failed to read logs for '{}': {e}", request.log_type);
                log::error!("{reason}");
                publish_final(client, topic, &original, "failed", Some(&reason)).await;
                return;
            }
        }
    };

    // Upload via thin-edge file-transfer service (HTTP PUT)
    match http
        .put(&request.tedge_url)
        .header("Content-Type", "text/plain")
        .body(content)
        .send()
        .await
    {
        Ok(resp) if resp.status().is_success() => {
            log::info!("Upload successful for type='{}'", request.log_type);
            publish_final(client, topic, &original, "successful", None).await;
        }
        Ok(resp) => {
            let reason = format!("HTTP upload returned {}", resp.status());
            log::error!("{reason}");
            publish_final(client, topic, &original, "failed", Some(&reason)).await;
        }
        Err(e) => {
            let reason = format!("HTTP upload error: {e}");
            log::error!("{reason}");
            publish_final(client, topic, &original, "failed", Some(&reason)).await;
        }
    }
}

/// Publish a final (successful/failed) status. Uses retain=true so the retained
/// "scheduled" message on the broker is replaced and the command won't be re-delivered.
async fn publish_final(
    client: &AsyncClient,
    topic: &str,
    original: &serde_json::Value,
    status: &str,
    reason: Option<&str>,
) {
    let payload = make_status_payload(original, status, reason);
    let _ = client.publish(topic, QoS::AtLeastOnce, true, payload).await;
}

/// Publish a retained health=up message with current PID and time.
async fn publish_health_up(client: &AsyncClient, pid: u32) {
    let time = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs_f64();
    let payload = format!(r#"{{"pid":{pid},"status":"up","time":{time}}}"#);
    let _ = client
        .publish(HEALTH_TOPIC, QoS::AtLeastOnce, true, payload)
        .await;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> Result<()> {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();

    let mqtt_host = env::var("TEDGE_MQTT_BIND_ADDRESS").unwrap_or_else(|_| "127.0.0.1".to_string());
    let mqtt_port: u16 = env::var("TEDGE_MQTT_CLIENT_PORT")
        .ok()
        .and_then(|p| p.parse().ok())
        .unwrap_or(1883);
    let config_path = get_config_path();
    let snap_data = env::var("SNAP_DATA").unwrap_or_default();

    log::info!(
        "tedge-log-upload-manager starting — broker={}:{}, config={}",
        mqtt_host,
        mqtt_port,
        config_path.display()
    );

    let mut mqttopts = MqttOptions::new(MQTT_CLIENT_ID, &mqtt_host, mqtt_port);
    mqttopts.set_keep_alive(Duration::from_secs(30));
    mqttopts.set_clean_session(true);

    let (client, mut eventloop) = AsyncClient::new(mqttopts, 100);
    let http = Client::new();
    let pid = std::process::id();

    // Register service and publish initial health=up (retained)
    let _ = client
        .publish(
            SERVICE_REG_TOPIC,
            QoS::AtLeastOnce,
            true,
            r#"{"@parent":"device/main//","@type":"service","name":"tedge-log-upload-manager","type":"service"}"#,
        )
        .await;
    publish_health_up(&client, pid).await;

    client
        .subscribe(LOG_UPLOAD_SUBSCRIBE, QoS::AtLeastOnce)
        .await?;
    client
        .subscribe(HEALTH_CHECK_TOPIC, QoS::AtLeastOnce)
        .await?;
    log::info!("Subscribed to {LOG_UPLOAD_SUBSCRIBE} and {HEALTH_CHECK_TOPIC}");

    // Initial announce right after startup
    announce_log_types(&client, &config_path).await;
    announce_installed_snaps(&client, &snap_data).await;

    // Delayed re-announce after 15s: tedge-agent may publish {"types":[]} on startup
    // (if no executable log plugin is found). We re-publish to overwrite.
    {
        let c = client.clone();
        let cp = config_path.clone();
        let sd = snap_data.clone();
        tokio::spawn(async move {
            tokio::time::sleep(Duration::from_secs(15)).await;
            announce_log_types(&c, &cp).await;
            announce_installed_snaps(&c, &sd).await;
        });
    }

    // Periodic re-announce every hour
    let announce_client = client.clone();
    let announce_config = config_path.clone();
    let announce_snap_data = snap_data.clone();
    tokio::spawn(async move {
        let mut interval = time::interval(Duration::from_secs(ANNOUNCE_INTERVAL_SECS));
        interval.tick().await; // skip first tick (already announced above)
        loop {
            interval.tick().await;
            announce_log_types(&announce_client, &announce_config).await;
            announce_installed_snaps(&announce_client, &announce_snap_data).await;
        }
    });

    // Main event loop
    loop {
        match eventloop.poll().await {
            Ok(Event::Incoming(Packet::Publish(p))) => {
                let topic = p.topic.clone();
                let payload = p.payload.to_vec();

                // Health check: respond immediately
                if topic == HEALTH_CHECK_TOPIC {
                    publish_health_up(&client, pid).await;
                    continue;
                }

                let c = client.clone();
                let h = http.clone();
                let cp = config_path.clone();
                tokio::spawn(async move {
                    handle_log_upload_request(&c, &h, &topic, &payload, &cp).await
                });
            }
            Ok(_) => {}
            Err(e) => {
                log::error!("MQTT connection error: {e} — retrying in 5s");
                tokio::time::sleep(Duration::from_secs(5)).await;
            }
        }
    }
}
